CREATE TABLE "Contract" (
    "id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'parsing',
    "fileName" TEXT NOT NULL,
    "filePath" TEXT NOT NULL,
    "rawText" TEXT,
    "contractName" TEXT,
    "partyACompany" TEXT,
    "partyARepresentative" TEXT,
    "partyAAddress" TEXT,
    "partyABusinessNo" TEXT,
    "partyBCompany" TEXT,
    "partyBRepresentative" TEXT,
    "partyBAddress" TEXT,
    "partyBBusinessNo" TEXT,
    "dataScope" TEXT,
    "recordCount" TEXT,
    "contractAmount" TEXT,
    "startDate" TEXT,
    "endDate" TEXT,
    "securityLevel" TEXT,
    "specialTerms" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Contract_pkey" PRIMARY KEY ("id")
);
